const EDIT_INFO_REQUEST = 'EDIT_INFO_REQUEST';
const EDIT_INFO_SUCCESS = 'EDIT_INFO_SUCCESS';
const EDIT_INFO_FAILURE ='EDIT_INFO_FAILURE';

export {
  EDIT_INFO_REQUEST ,
  EDIT_INFO_SUCCESS,
  EDIT_INFO_FAILURE,
}
