const FORGOT_API_REQUEST = 'FORGOT_API_REQUEST';
const FORGOT_API_SUCCESS = 'FORGOT_API_SUCCESS';
const FORGOT_API_FAILURE = 'FORGOT_API_FAILURE';

export {
  FORGOT_API_REQUEST,
  FORGOT_API_SUCCESS,
  FORGOT_API_FAILURE,
}
