const INFO_API_REQUEST = 'INFO_API_REQUEST';
const INFO_API_SUCCESS = 'INFO_API_SUCCESS';
const INFO_API_FAILURE = 'INFO_API_FAILURE';
export {
  INFO_API_REQUEST,
  INFO_API_SUCCESS,
  INFO_API_FAILURE,
}
