const LIST_API_REQUEST = 'LIST_API_REQUEST';
const LIST_API_SUCCESS = 'LIST_API_SUCCESS';
const LIST_API_FAILURE = 'LIST_API_FAILURE';

export {
  LIST_API_REQUEST,
  LIST_API_SUCCESS,
  LIST_API_FAILURE,
}
