const READ_API_REQUEST = 'READ_API_REQUEST';
const READ_API_SUCCESS = 'READ_API_SUCCESS';
const READ_API_FAILURE = 'READ_API_FAILURE';
export {
  READ_API_REQUEST,
  READ_API_SUCCESS,
  READ_API_FAILURE,
}
