const SIDE_BAR_REQUEST = 'SIDE_BAR_REQUEST';
const SIDE_BAR_SUCCESS = 'SIDE_BAR_SUCCESS';
const SIDE_BAR_FAILURE = 'SIDE_BAR_FAILURE';
export {
  SIDE_BAR_REQUEST,
  SIDE_BAR_SUCCESS,
  SIDE_BAR_FAILURE,
}
